server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: nft-service
          uri: lb://NFTSERVICE
          predicates:
            - Path=/nft/**
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: bidding-service
          uri: lb://BIDDINGSERVICE
          predicates:
            - Path=/bidding/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka