server:
  port: 8085

spring:
  application:
    name: ConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/duveshp/micro-config-server
          clone-on-start: true